### ISSUE TITLE
Support column preview grpc call

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#107]
Presently ColumnPreviewManager is always used to replace some columns which potentially aren't friendly for the UI - this is irritating to not be able to opt out of (yes a preview table has an attribute you can fetch, but wouldnt opt-in be nicer, esp for non-UI console commands)?

**Comment by nbauernfeind** [comment]
Charles points out that maybe we shouldn't auto-to-string non-ipc friendly columns. It actually ties well with this issue (i.e. the "can't opt out") and it might otherwise be confusing that a column keeps showing up as a string when do you want to transfer structured content. It was a choice we had made to be friendlier to the UI.

**Comment by nbauernfeind** [comment]
This is going to be addressed with Barrage Column Conversion modes. There are hooks in place, but no implementation yet: https://github.com/deephaven/deephaven-core/issues/936. Closing this ticket in favor of the other as it is less defined and less clear.
