### ISSUE TITLE
Python bad matching by with list

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#1102]
Jpy is matching the wrong method when provided with a python list in the by case.

`Table.by(Collection<? extends Selectable> groupByColumns)`

```python
from deephaven import TableTools
import jpy

ColumnName = jpy.get_type('io.deephaven.api.ColumnName').of
AsList = jpy.get_type('java.util.Arrays').asList

works = TableTools.timeTable("00:00:01")\
    .updateView("I=i%4")\
    .by(AsList(ColumnName("I")))

broken = TableTools.timeTable("00:00:01")\
    .updateView("I=i%4")\
    .by([ ColumnName("I") ])
```

```
Type: <class 'ValueError'>
Value: cannot convert a Python 'io.deephaven.api.ColumnName' to a Java 'io.deephaven.db.v2.select.SelectColumn'
```

This error suggests that jpy is trying to call `Table.by(SelectColumn... groupByColumns)`

**Comment by devinrsmith** [comment]
May be related to #1101

**Comment by jmao-denver** [comment]
after some code studying, I have come to believe it is the fact that groupByColumns is a  'generic' that led JPY to choose the 'wrong' overload version. It is very logical that when matching overload methods based on the passed-in Python values, JPY gives more specific types priority over 'generic' types. And because it doesn't backtrack when a chosen version fails, once it sees a best match, it will try to convert the Python object to the specified Java type of the parameters.

two paths forward: 
1. it may be possible for us to enhance the generic type support of JPY without breaking backwards compatibility
2. manual wrapper for the Table class as @devinrsmith 's work case suggests.

I prefer  2 as it is much safer and much less work.

**Comment by jmao-denver** [comment]
The same error happened when I tried to use SortColumn instead SortPairs in the new table wrappers. In the db-module-refactor project, Ryan removed the use of SortPairs in the table interface but ran into the 'no matching overloads found' issue reported in #1101.
