### ISSUE TITLE
Python unit tests are non-deterministic

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#1635]
Python unit tests use sleeps, which make them non-deterministic.  For example:

```
    def test_snapshot_timetable(self):
        t = self.session.time_table(period=10000000)
        time.sleep(1)
        pa_table = t.snapshot()
        self.assertGreaterEqual(pa_table.num_rows, 1)
```

**Comment by chipkent** [comment]
Better to get @rcaudy 's thoughts.

**Comment by rcaudy** [comment]
My thoughts haven't changed since the last time we discussed something like this. Don't rely on sleeps to guarantee asynchronous behavior in unit tests.
There are exactly two ways forward for this test:
1. Use the existing UGP unit test support to control the refresh behavior, and thereby ensure that the `TimeTable` refreshes after the desired time has elapsed.
2. Delete this test. It seems to be trying to test the correct behavior of `TimeTable`, which is better done from Java on the engine side. You can test an initial value if you want, but it's not clear that this is a meaningful unit test for the Python wrapper.

**Comment by rcaudy** [comment]
Revising my comment. I thought this was a test for the server-side wrappers. On the client you don't have the option to control the server's UGP. The test should just be deleted, or revised to not expect data to tick.

**Comment by jmao-denver** [comment]
fixed by PR/1679
