### ISSUE TITLE
JS ChartData type doesn't handle shifts correctly

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#2435]
Not the prettiest query, but it seems to get the job done.

Create the following ticking table, and then use chart builder to create a bar chart with TimeBin on x-axis and Count on y-axis, w/ sync'd state. Add a quick-filter on M is equal to 8. The chart will likely tick correctly for a little bit, but then some it will likely stop ticking and will show incorrect data.

```groovy
t = timeTable("00:00:00.001")
  .updateView("TimeBin=lowerBin(Timestamp, 1000000000)", "I=i", "K=i%3+i%5+i%7+i%11", "M=K%3+K%5+K%7+K%11")
  .sort("M")
  .countBy("Count", "TimeBin", "M")
  .sort("M")
```

![image](https://user-images.githubusercontent.com/6764691/169161741-9fffa483-2132-48aa-abfa-03747bcdbd4b.png)

A similar demonstration has been achieved w/ pie chart.

**Comment by niloc132** [comment]
The underlying issue is SubscriptionTableData doesn't propagate shifts to consumers, like TableData, so the data is broken if shifts appear. Apparently this has always been broken, since shifts were introduced.

The easiest fix to consume by JS would be to normalized shifts into add/modify/removes in the existing event, but the most efficient would be to propagate them to TableData to avoid unnecessary data operations. Adding a "shiftObliviousListener" sort of helper here might be best, so that TableData can get the most efficient code, and JS consumers can opt out of handling shifts.

**Comment by devinrsmith** [comment]
I wonder if we should do an audit of listeners to see if there are any other obvious spots that are missing shift handling :s
