### ISSUE TITLE
The '@auto_locking_op' annotation breaks autocomplete

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#2639]
The `@auto_locking_op` annotation interferes with InetlliJ's ability to understand and autocomplete Python code.

You can see from this screenshot that the arguments for many methods are missing (and when writing code using these methods, you're unable to see the parameters:

![image](https://user-images.githubusercontent.com/9516585/179256323-8304f83c-fe95-4810-bdc2-9b06055ed940.png)

![image](https://user-images.githubusercontent.com/9516585/179257070-b5aa4bb9-e02d-4544-a423-e76f8fe6c440.png)

The results of these methods are not identified as Tables, either, so you lose autocomplete on subsequent method calls:

![image](https://user-images.githubusercontent.com/9516585/179256892-e76d6e8a-35fb-467b-bdbd-8a178b0a9422.png)

Rebuilding a `deephaven-core` wheel with the annotations removed from `table.py` fixes the issue:

![image](https://user-images.githubusercontent.com/9516585/179257425-ea4198a5-5ae1-47a4-a9ee-ff07e2df74f0.png)

**Comment by jmao-denver** [comment]
The first problem surely looks to be with Intellij/PyCharm as reported here https://intellij-support.jetbrains.com/hc/en-us/community/posts/4421575751442-Code-Completion-doesn-t-work-for-class-functions-decorated-with-decorators-that-return-inner-functions. I tried it with VSCode and it suffers the same problem.  Overall I have not found enough user complains and little sympathy among IDE vendors. Technically there might be reasons why this is not as clear cut as we would hope because a decorator could definitely have a different signature and may be used to obfuscate the wrapped function. An alternative for us is to move the auto-locking logic inside each of the decorated function, but it is not as elegant and pythonic as using the decorator.

The 2nd problem is solvable by providing a return type in the decorator's type hints.

**Comment by rbasralian** [comment]
Is this what [this JetBrains issue](https://youtrack.jetbrains.com/issue/PY-37362/Infer-types-of-decorated-methods-based-on-the-type-hints-of-their-decorators#focus=Comments-27-5802490.0-0) is about?

Anyway I think we should just move the logic into the functions, I agree that it's not ideal but it's worth it if it works around the IDE bugs.

**Comment by jmao-denver** [comment]
@rcaudy @chipkent I'd like to hear your thoughts. The combined number of the auto-locking applicable operations between Table and PartitionedTableProxy isn't small (50+), surely looks to be a maintenance disaster to boilerplate so many with the auto-locking logic code 

> Is this what [this JetBrains issue](https://youtrack.jetbrains.com/issue/PY-37362/Infer-types-of-decorated-methods-based-on-the-type-hints-of-their-decorators#focus=Comments-27-5802490.0-0) is about?
> 
> Anyway I think we should just move the logic into the functions, I agree that it's not ideal but it's worth it if it works around the IDE bugs.

**Comment by chipkent** [comment]
Autocomplete is critical.  It has to work very well, even if it increases dev problems.
@mofojed said that he just used autocomplete in VS code without a problem.

1) Can we confirm that the latest VS Code works?
2) Have we tried the most recent PyCharm?
3) Does the quality of autocomplete depend on the python version that is selected?
4) Does this help?  https://peps.python.org/pep-0612/
5) Does this help?  https://github.com/davidhalter/jedi/issues/1425#issuecomment-565711589
6) Useful at all?  https://stackoverflow.com/questions/71031173/type-hinting-for-a-function-wrapping-another-function-accepting-the-same-argume

Moving the autolock logic into the functions is a heavy hammer, but we may be forced to use it.
