### ISSUE TITLE
Python type inference can be improved

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#2744]
In python, DH requires explicit type casting way too often.  The only case where type inference is automatically performed is `numba` with `@vectorize`.  It is possible to improve the user experience.

1) Use python type hints to determine output types.
2) Use `numba` `jit` annotations to determine output types.
3) Use non-type annotated `numba` cases to determine output types.

For plain python without annotations or `numba`, is there any way to get type inference?  I'm guessing not easily or efficiently, but there are some possibilities for inferring return types.
1) [pyright type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md)
2) [type4py](https://arxiv.org/abs/2101.04470) e.g. [here](https://github.com/saltudelft/type4py)
3) [mypy](https://github.com/python/mypy)

```python
from numba import jit, vectorize, double, int64
from deephaven import empty_table

def mult1(a,b):
    return a*b

def mult2(a:int,b:int)->int:
    return a*b

@jit
def mult3(a,b):
    return a*b

@jit
def mult4(a:int,b:int)->int:
    return a*b

@jit(int64(int64, int64))
def mult5(a:int,b:int)->int:
    return a*b

@vectorize([int64(int64, int64)])
def mult6(a:int,b:int)->int:
    return a*b


t = empty_table(10).update(["X=i","Y=i%2==0?i:-i","Z1=mult1(X,Y)","Z2=mult2(X,Y)","Z3=mult3(X,Y)","Z4=mult4(X,Y)","Z5=mult5(X,Y)","Z6=mult6(X,Y)"])

m = t.meta_table
```
<img width="493" alt="image" src="https://user-images.githubusercontent.com/5250374/185643446-0fdc146a-6169-401a-9dac-bf5cefab9ee8.png">

Type hints should support this case:
* https://stackoverflow.com/questions/65558428/python-typing-mypy-infer-return-type-based-on-class-method-return-type
* https://stackoverflow.com/questions/72141966/infer-type-from-subclass-method-return-type

**Comment by jmao-denver** [comment]
The WIP chunking work supports return-type inference via annotation, it is a first step in the right direction. Some notable cases that this approach doesn't address:

- third party functions/methods without annotations. Python built-in functions are less of a concern because they can usually find an equivalent in Java and we should always use the Java ones.
- advanced type inference based on generics which is supported by mypy or other static type checkers. However, using them (if possible) isn't without any downsides, as they can be time-consuming thus increase the up-front overhead of formula evaluation quite a bit and the results are not guaranteed to be perfect.

At this moment, I am inclined to close this ticket with the merge of #2929.

**Comment by chipkent** [comment]
I think you are asking if we should use `mypy` or something similar to infer return types of python functions.  I do think this is a good idea since most Python devs have not yet adopted type hints.

To understand how important this is, @jjbrosnan can look at our docs to see how many of the python casts can be removed after 2929.
