### ISSUE TITLE
Use the fill context pattern to pre-allocate memory storage for the chunk input to avoid repeated allocation 

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#2948]
Currently the fill context

**Comment by rcaudy** [comment]
Maybe this ticket was supposed to be:
1. When doing vectorized evaluations in Python, use `fillChunk` pattern instead of a `getChunk` pattern for retrieving inputs.
2. Allocate our own backing arrays and pass them down, so that we can avoid having to copy the chunks into arrays for calling our vectorized Python function.
