### ISSUE TITLE
Autocomplete suggestions overwrite existing text instead of inserting

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3363]
**Description**

When using Python autocomplete, the suggestions overwrite existing text rather than insert it.

**Steps to reproduce**
1. Enter the following snippet of code in the console, but do not submit the command:
```
from deephaven import emtpy_table
t = empty_table(10).update(["x=i"])
```
2. Put the cursor after `.update` and change it to `.update_`, then select `.update_view` from the suggestion menu (see video).

**Expected results**
2. The snippet should update to `.update_view`, i.e.
```
from deephaven import emtpy_table
t = empty_table(10).update_view(["x=i"])
```

**Actual results**
2. The update_view overwrites part of the formula, and the resulting text is:
```
from deephaven import emtpy_table
t = empty_table(10).update_view=i"])
```

**Additional details and attachments**

![autocomplete-overwrite](https://user-images.githubusercontent.com/4505624/214919962-0caec66c-181a-41ef-92c6-5acfbebfd740.gif)

**Versions**
Engine Version: 0.21.0
Web UI Version: 0.26.1
Java Version: 17.0.5
Barrage Version: 0.5.0

**Comment by mattrunyon** [comment]
The issues appears to be that the range set for the text edit is set as the resulting range and not the editing range. We're also not following the LSP spec w/ the naming of the edit text. We just use `text` and not `newText` for that field.

The range should be the original word range that is being replaced. In the above, `update_` is something like [20, 26] as its range. The text edits returned should both have a range [20, 26] since they are meant to replace `update_` with the `newText`

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit
