### ISSUE TITLE
CI failure for booleanAsByte

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#3461]
We seem to be resolving the wrong overload for `BooleanUtils.booleanAsByte` at least some of the time.
https://scans.gradle.com/s/ig3cve3w726uw/tests/:engine-table:testOutOfBand/io.deephaven.engine.table.impl.sources.regioned.TestChunkedRegionedOperations/testSparseTableSmallChunks?top-execution=1

**Comment by nbauernfeind** [comment]
`QueryLanguageParser#isMoreSpecificExecutable` has a hard time differentiating between:
- `BooleanUtils#booleanAsByte(Boolean)`
- `BooleanUtils#booleanAsByte(boolean)`

It believes that both methods are more specific than the other, since boolean and Boolean can be cast to one another.

I believe the appropriate fix will involve the context of the actually provided argument types and penalize casts.

This is only fails sometimes as behavior depends on the order that java reflection visits the two methods.
