### ISSUE TITLE
Change aj/raj in Python API to match the recent changes in the Java API.

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3560]
In Java/Groovy, aj/raj have been improved to support join expressions other than equality. 
```
j2 = myTrades.aj(t, ["Timestamp<Timestamp"], ["PriceBeforeMyTrade=Price"]).view(["Sym", "Price", "PriceBeforeMyTrade", "Timestamp"])
```

**Comment by devinrsmith** [comment]
Essentially, I think we want to drop `match_rule: AsOfMatchRule = ...` from the python aj / raj methods, since AsOfMatchRule only makes sense when you are already dealing w/ `JoinMatch` objects. 

When using `io.deephaven.api.expression.AsOfJoinMatchFactory`, it will correctly be able to parse the last column with an appropriate alternative comparison string.

**Comment by rachelmbrubaker** [comment]
Per convo here: https://illumon.slack.com/archives/C04KEKKPMJT/p1679070625810289

DHE expects this change be ready for DnD for Vermilion

**Comment by rachelmbrubaker** [comment]
Also note that changes should incorporate docs, if not already covered by https://github.com/deephaven/deephaven.io/issues/2291
