### ISSUE TITLE
Allow two-way communication between UI and server for plugins

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3583]
As a developer, I want to be able to create a plugin that can communicate between the backend/frontend so that we can have some more interactive plugins.

Currently, we can pass tables from the server to the client, and those tables can update. However, for sending data from the client back to the server/plugin, there's nothing we can do. I've tried some experiments with input tables, but they were both cumbersome and did not work reliably.

This is a requirement for programmatic layout support (#2774), and for other things like allowing interactive matplotlib plots or real-time matplotlib updates (#2078).

How the communication gets implemented is an open discussion. If we did something like allow websockets, it may allow integration with existing frameworks easily (such as [matplotlib's WebAgg interactive plotting](https://matplotlib.org/stable/gallery/user_interfaces/embedding_webagg_sgskip.html)), though there may be security implications and other concerns. Using something like input tables may be easy, but it may make integrations more difficult and/or have other limitations.

**Comment by mattrunyon** [comment]
Here's my thoughts for the API and some sequence diagrams which might be useful to add to plugin docs

### Overview of Plugins and Widget fetching

```mermaid
sequenceDiagram
  participant U as User
  participant S as Server
  participant P as Plugins
  participant O as Object
  participant W as Web IDE
  participant J as JS Plugins
  P ->> S: Register
  U ->> S: Run code
  S ->> P: is_type(object)
  P ->> S: Matching plugin
  S ->> W: Objects
  W ->> J: Panel open event
  J ->> S: Fetch object info
  S ->> P: serialize(object)
  P ->> O: serialize
  O ->> P: Payload
  P ->> S: Payload
  S ->> J: Widget
  J ->> W: Display panel
```

### Establishing BiDi Communication

```mermaid
sequenceDiagram
  participant S as Server
  participant P as Plugins
  participant O as Object
  participant J as JS Plugins
  J ->> S: Fetch object info
  S ->> J: Widget
  J ->> S: Open BiDi Channel
  S ->> P: attachChannel(object)
  P ->> O: attachChannel
  S ->> J: BiDi Channel
```

### Server message

```mermaid
sequenceDiagram
  participant S as Server
  participant O as Object
  participant B as BiDi Channel
  participant J as JS Plugins
  J ->> B: addEventListener
  O ->> S: Send message
  S ->> B: Send message with exports
  B ->> J: Message event
  J ->> J: Handle message
```

### Client message

```mermaid
sequenceDiagram
  participant S as Server
  participant P as Plugins
  participant O as Object
  participant B as BiDi Channel
  participant J as JS Plugins
  J ->> B: Send message
  B ->> S: Message
  S ->> P: Message w/ object
  opt implements handle_message
    P ->> O: Message
  end
```

### Python/Groovy plugin

Plugin object - The single instance class which is used to register the plugin w/ the server. Server communicates w/ this class

Object - The Python object that a user creates via code which will be exported as a widget

The plugin object will delegate messages to the specific object by default. This will probably cover most simple use cases, and more advanced use cases (like having the plugin object do some extra routing/handle the messages itself) can be added by extending the ObjectType class.

There should probably be a new base object for Python which the objects for the plugin can extend to indicate they implement the bidirectional communication interface. The object needs to have some way to communicate with the plugin object or at least indicate it knows how to handle the methods from the plugin object. The methods for adding and removing the message sender can have default implementations in this base class and then the plugin author only needs to implement the message handler.

The object should be able to send messages at any point. It should also be able to export objects with the message. These objects may have already been exported, so we should try to keep the ticket for the objects unless `forceNew` is specified. We will also need some way of cleaning up the exports from the object as they become unused.

It's probably a good idea to maintain a single export collector across the messages for the life of an object. This way, the tickets are easily accessed and can be used as a way to tell the client any extra info about an export.

Any time an export is added or fetched from the collector, it is added to a set of exports since the last message. That set should be sent on next message. The object could also explicitly remove an export to tell the client. Maybe we want to also add a `replace` method to the export collector so we can tell the client "Replace A with B". Any modified or referenced exports should be sent on message so we only send things with updates.

```python
class ObjectType:
  def add_message_sender(self, object: Object, sender):
    # Tells the object to add the message sender if it extends BiDiObject
    # Called from the server when the channel is opened

  def remove_message_sender(self, object: Object):
    # Tells the object to remove the message sender if it extends BiDiObject
    # Called from the server when the channel is closed

  def handle_message(self, msg: str, object: Object, objects: Object[]):
    # Delegates the message to the specific object instance if it extends BiDiObject

class BiDiObject:
  # Abstract class used to provide default message sending handling
  # The default should be good for most typical use cases

  def add_message_sender(self, sender):
    # Default impl of adding the message_sender to this class

  def remove_message_sender(self):
    # Removes sender from this class. Effectively prevents the object from sending messages again

  def export(self, obj: Object):
    # Should add 

  def send_message(self, msg: Union[str, bytes], only_new_objects=True):
    # Lets the object send a message to the client
    # Message can be a string (this function should encode as UTF-8) or already encoded byte array
    # 

class MyPluginObject(BiDiObject):
  def handle_message(self, msg: str, objects: Object[]):
    # Called by the server whenever it receives a message from the client
  
```

### JS Client

Add an event listener to receive messages from the server. The event detail should contain an object with a getter for the message (auto decode as UTF-8 string), raw message (byte array), exported objects (not sure if all objects the plugin instance references or just new since last message), and possibly deleted objects/modified objects. Basically make it easy for the server to tell the client which objects it might need to refetch or can stop tracking.

The client should be able to send a message on the JsWidget. That message can be a Uint8Array or string which will be encoded to a Uint8Array. The client can optionally provide objects (tickets?) that are part of the message

```ts
interface JsWidget extends HasEventHandling {
  fetch(): Promise<JsWidget>;
  addEventListener(type: string, handler: (e: CustomEvent<MessageDetail>) => void): void;
  sendMessage(msg: string | Uint8Array, objects?: Ticket[]): void;
}

interface ExportedObject {
  fetch(): Promise<JsWidget>;
}

interface MessageDetail {
  get message(): string; // Will try to parse message as UTF-8 to handle most use cases
  get rawMessage(): Uint8Array; // Can be used if a different encoding is desired
  get exportedObjects(): ExportedObject[]; // Should this contain just new objects, or all objects the plugin has exported?
  get deletedObjects(): Ticket[]; // Maybe? Or should this be part of the message
}
```
