### ISSUE TITLE
Add ByteBuffer support in JPY to give DH  direct access to pyarrow data

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3709]
1. cut the number of data copies by 1 or achieve zero-copy when ingesting arrow data from Python
2. possibly allow arrow data created by in Python to be arrow-backed ColumnSource

**Comment by niloc132** [comment]
I'm not sure anything would fit better than ByteBuffer, since there is explicit JNI support for java passing a ByteBuffer into C, which we could then directly use as a python Buffer, and vice versa, a python Buffer could be used to construct a java ByteBuffer before calling back into Java.

See:
* https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer
* https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#GetDirectBufferAddress
* https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#GetDirectBufferCapacity

Passing a `byte[]` is "free", since it behaves more or less like a python iterable of bytes - like bytes/bytearray/memoryview/bytestring. However, it isn't actually one of those, is missing instance methods, etc. Wrapping in a memoryview is cheap (only requiring python code instead of being seamless).

On the other hand, sending something back to Java where a `byte[]` is expected appears cheap (most/all of the above python types works), but actually performs a copy of the data into a new `byte[]` instance - in contrast to the above, this is entirely seemless, but is expensive.

If jpy offered recognized python buffers and java ByteBuffers as "an address and a length" and correctly wrapped/unwrapped for usage on each side, we could have both seamless API usage (the python author would need to dress up the buffer as they saw fit to use it, or use it directly as an iterable of bytes), without any copying.
