### ISSUE TITLE
remove or replace custom junit-wall / jmock-wall dependencies

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#380]
These are private jars in artifactory. Need to replace.

**Comment by niloc132** [comment]
This is not fixed, and is presently a source of java 17/18 test failures, since the jmock/cglib versions are far too old to work in java 17/18. 

cglib is now unmaintained and not expected to be updated, see https://github.com/cglib/cglib#cglib- and https://github.com/cglib/cglib/issues/191.

JMock apparently still works, but it will need to be a much newer version. Going by the issue tracker, it might not keep going much longer, it is long overdue for a release.
