### ISSUE TITLE
Expose More Control over ClientConfig

### ISSUE THREAD

**Issue by cpwright** [deephaven/deephaven-core#3834]
As a software integrator, I want to be able to control the details of my flight client SSL channel so that I can deploy in a variety of environments.  The io.deephaven.client.impl.ClientConfig does not expose overrideAuthority.  Letting us have more direct access to the channel builders would mean that we do not need to have a Deephaven community release for each change that we would want to configure.

A useful possibility would be passing in a lambda that allows us to modify the builder before it is built.

**Comment by devinrsmith** [comment]
This is a reasonable request.

There are some choices we'd want to make on the spectrum of `ClientConfig` provides one-to-one parity for everything that can be done via `io.grpc.ManagedChannelBuilder` vs `ClientConfig` is simple and works the majority of time, but there is an escape hatch (lambda, or otherwise) that allows more advanced configuration.

I can't say exactly, but "overrideAuthority" might also interact w/ `io.deephaven.client.impl.DeephavenTargetNameResolverProviders.Secure`.

If we were to provide an "advanced integrators escape hatch", I think making the whole call the interface would be better than adding a new parameter to the existing methods:

```java
interface ManagedChannelFactory {
    // Default impl delegates to io.deephaven.client.impl.ChannelHelper#channel
    ManagedChannel build(ClientConfig config);
}

And then allow integrators to provide this via dagger and/or service loader.
