### ISSUE TITLE
Creating parquet table partitioned on a boolean column throws error

### ISSUE THREAD

**Issue by georgecwan** [deephaven/deephaven-core#4545]
**Description**

Creating a parquet table partitioned on a column of `boolean` type and then running `j_object.getColumnSources()` will cause an exception.

**Steps to reproduce**
1. Run the following code snippet:
```python
from deephaven import empty_table

part = empty_table(4).update("II=ii")

from deephaven.parquet import write, read

write(part, "/tmp/bool-test/boolCol=true/part.parquet")
write(part, "/tmp/bool-test/boolCol=false/part.parquet")

bool_partition = read("/tmp/bool-test")
```
2. Run `bool_partition.j_object.getColumnSources()`

**Comment by niloc132** [comment]
I think this is a Java bug - readPartitionTableInferSchema always unboxes primitives instead of handling boolean specially:
https://github.com/deephaven/deephaven-core/blob/0d17b643f7ccf7c602036ac280ed4ec74cebecac/extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetTools.java#L688-L689

Contrast with ParquetMetadataFileLayout's adjustPartitionDefinition, which special cases boolean:
https://github.com/deephaven/deephaven-core/blob/0d17b643f7ccf7c602036ac280ed4ec74cebecac/extensions/parquet/table/src/main/java/io/deephaven/parquet/table/layout/ParquetMetadataFileLayout.java#L222-L239
