### ISSUE TITLE
BUG: plotByOHLC does not accept Instants as open/close time params

### ISSUE THREAD

**Issue by elijahpetty** [deephaven/deephaven-core#4603]
This is a potential bug with the `plotByOHLC` method. This query:

```
import static io.deephaven.csv.CsvTools.readCsv
import static io.deephaven.api.agg.Aggregation.AggAvg

cryptoTrades = readCsv("https://media.githubusercontent.com/media/deephaven/examples/main/CryptoCurrencyHistory/CSV/CryptoTrades_20210922.csv")

agg_list = [
    AggLast("CloseTime = Timestamp"),\
    AggFirst("OpenTime = Timestamp"),\
    AggMax("High = Price"),\
    AggMin("Low = Price"),
]

btcBin = cryptoTrades.where(FilterOr.of(Filter.from("Instrument = `BTC/USD`", "Instrument = `ETH/USD`"))).update("TimestampBin = lowerBin(Timestamp, MINUTE)")
tOHLC = btcBin.aggBy(agg_list, "Instrument", "TimestampBin")

plotByOHLC = ohlcPlotBy("Instrument", tOHLC, "TimestampBin", "OpenTime", "High", "Low", "CloseTime", "Instrument").show()
```

Causes this error in the last line: 
"r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: io.deephaven.plot.errors.PlotRuntimeException: Plot Information: Chart: . Series: Instrument. Invalid data type in column = OpenTime. Expected one of [], was class java.time.Instant"

Instants should work.

**Comment by chipkent** [comment]
I have analyzed this bug report, and it is a problem in the script above and not the code.  

The script is computing an OpenTime and a CloseTime instead of an OpenValue and a CloseValue.  Because the OpenTime and CloseTime are times instead of numerical values, the error is raised.

<img width="1670" alt="image" src="https://github.com/deephaven/deephaven-core/assets/5250374/e912ca46-cd4c-4c26-a9bc-f263682479f0">

The error message was cryptic, so that has been addressed in #4698.
