### ISSUE TITLE
Support array-like inputs for `to_j_*` functions in `deephaven.time`

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#4729]
I would like to be able to call `to_j_instant()` or `to_j_period()` (and the rest) on an array-like python structure and have the result be a Java array of the correct type, so long as all of the elements of the python structure are of an acceptable type for that function. For example:

```
from deephaven.time import to_j_period
import deephaven.dtypes as dht
import datetime as dt
import numpy as np
import pandas as pd

data = ["P5Y4W3D", dt.timedelta(days = 1856), np.timedelta64(1856, "D"), pd.Timedelta(days = 1856)]

# this works
j_data = [to_j_period(period) for period in data]
j_array = dht.array(dht.Period, j_data)

# I think this should work, and be identical to j_array
j_array = to_j_period(data)
```

I see no reason to not support the latter, and I personally expected the latter to work before trying it and reading the code. Another two related examples (in the first, note that `DatetimeIndex` is pandas' array equivalent of the `Timestamp`):

```
from deephaven.time import to_j_instant
import pandas as pd

data = pd.DatetimeIndex(["2022-07-01T12:00:00", "2022-07-01T13:00:00", "2022-07-01T14:00:00"])

# this works
j_data = [to_j_instant(datetime) for datetime in data]
j_array = dht.array(dht.Instant, j_data)

# I think this should work, and be identical to j_array
j_array = to_j_instant(data)
```

```
from deephaven.time import to_j_local_time
import numpy as np

data = np.arange(np.datetime64("2022-07-01T12:00:00"), np.datetime64("2022-07-01T15:00:00"), np.timedelta64(1, "h"))

# this works
j_data = [to_j_local_time(datetime) for datetime in data]
j_array = dht.array(dht.LocalTime, j_data)

# I think this should work, and be identical to j_array
j_array = to_j_local_time(data)
```

I would go as far as to say that this is _the_ use case. Who has isolated scalar datetime values? I've never seen them not come in array-like structures in real data.
I also think we should be able to convert back from Java to Python in an array-like fashion, but that is a different discussion.

**Comment by jmao-denver** [comment]
1. This ticket points out some gaps in how we handle the conversion between Python date/time data and the Java ones 
      - Right now `dtypes.array` only supports `Instant` not `Period`, `LocalTIme`, `ZonedDateTime`. A user shouldn't have to call the `to_j_xxx` functions to convert a scalar Python date/time value to the equivalent Java one first in order to create a Java array of them.
      -  Python UDF return type inference doesn't yet support the aforementioned types.

2. I'd prefer to have a single function in the API to handle the creation of arrays of datetime data, much like numpy.array, etc. Right now that's `dtypes.array` in Deephaven Python API. 
3.  While the `to_j_xxxxxx` suite of functions don't seem to be particularly useful to the users because they only work on scalar data, to expand what they do to support converting a sequence of Python data/time data to Java arrays, although might be convenient for some users, would make them overlap with what `dtypes.array` does. In general, when we design an API, we want to avoid that.

**Comment by chipkent** [comment]
Current decision: WNI
