### ISSUE TITLE
Attempting to copy 100,000 rows only copies 50,000, does not throw an error.

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#4977]
**Description**

When you try to copy 100,000 rows, it only copies 50,000.

**Steps to reproduce**
1. Create a table with 100,000 rows, e.g.
```
from deephaven import empty_table
t = empty_table(100000).update(["X=i", "Y=i*i"])
```
2. In the table, press Ctrl+A to select all, then Ctrl+C to copy. Click "Copy" when prompted to confirm the copy of 100,000 rows.
3. In a text pad, paste the result

**Expected results**
3. 100,000 rows pasted

**Actual results**
3. Only 50,000 rows are pasted

**Versions**

Engine Version: 0.32.0-SNAPSHOT
Web UI Version: 0.57.1
Java Version: 11.0.21
Barrage Version: 0.6.0

**Comment by mofojed** [comment]
It seems to cap at 60,000, even if I build a table with more columns, or only request 60,000 rows.
Also this is affecting Core workers on Enterprise, would upgrade this so a severe issue as it's erroneous data (think you're copying the whole table when you're not).

**Comment by mofojed** [comment]
Should patch this in 0.30.5 for Enterprise/Vermilion as well.

**Comment by niloc132** [comment]
This seems to be tied to `BarrageUtil.minSnapshotCellCount` defaulting to 50000, but oddly enough while that is a _cell_ count, we're seeing it as a row count, regardless of how many columns (and so cells) there are.

JS API is wrong here, #188 will enable it to handle more than one separate snapshot before having the initial amount of data. We should be able to detect this case from the JS API and emit an error instead of claiming success with partial data. Raising the min and max snapshot cell count should make it possible for the server and client to get along here.

Another solution would/should be the web UI asking for smaller snapshots - very wide rows will end up eventually breaking with the above limits raised. This is what the csv export does, even with "smaller" exports.

**Comment by mofojed** [comment]
@niloc132 can we please get a PR to throw an error if the snapshot is too big? This is marked as a blocker for Enterprise.

**Comment by niloc132** [comment]
This should be fixed by https://github.com/deephaven/deephaven-core/pull/4985, at least until #188 is complete when we can revert the server-side workaround.
