### ISSUE TITLE
The auto conversion feature of the Python UDF decorator has a performance problem.

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#5112]
This was found by the latest bench marking effort to measure the performance impact from the usability improvement on Python UDF.

**Comment by stanbrub** [comment]
Just to be clear, there are multiple issues that can be seen in testing between 0.24.0 and 0.32.0.  (Though the regression happens earlier than 0.32.0 and later than 0.24.0, these are the versions that are like what HH is seeing.)
Performance:
- Between 0.24.0 to 0.32.0 UDFs regressed by orders of magnitude
- For 0.32.0 (and probably the previous release) adding hints to UDF args makes things worse
- The performance regression happens for both arrays and scalars
- Unable to reproduce UDF regression in Groovy
Memory:
- Running the same UDF test back-to-back causes OOM, even if the test explicitly deletes table and runs GC
- Unable to reproduce memory issue in Groovy

**Comment by jmao-denver** [comment]
@stanbrub Can you confirm that performance degradation for scalars is on the same scale as for arrays?

**Comment by chipkent** [comment]
The title lists a "memory leak" and a "performance problem".  The example in the thread clearly shows a memory leak, but it looks like the rows/sec remains constant.  Is there another reproducer of the "performance problem", or is the performance problem just a slowdown that happens as the process runs out of memory.

**Comment by stanbrub** [comment]
Here are some results that show UDF performance regression between 0.24.0 and 0.32.0 for both scalar and array values
- There are large performance regressions for UDFs with no type hints
- Adding type hints makes the performance loss even bigger
- All tests were run with released docker images in the console in 24G Heap on x86 w/ 24 CPU threads

![udf-scalar-vs-array_0 24 0-vs-0 32 0](https://github.com/deephaven/deephaven-core/assets/120737309/601eaf74-3e69-4b39-94c5-524c4ff8588c)
[udf-array-no-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175097/udf-array-no-hints.py.txt)
[udf-double-scalar-no-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175098/udf-double-scalar-no-hints.py.txt)
[udf-single-scalar-no-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175099/udf-single-scalar-no-hints.py.txt)
[udf-single-scalar-with-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175100/udf-single-scalar-with-hints.py.txt)
[udf-double-scalar-with-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175101/udf-double-scalar-with-hints.py.txt)
[udf-array-with-hints.py.txt](https://github.com/deephaven/deephaven-core/files/14175102/udf-array-with-hints.py.txt)

**Comment by stanbrub** [comment]
Here's some more supporting info on the performance regression.  I ran some Benchmark UDF tests on >= 0.28.0.  
- There are two regressions; with the release of 0.29.0 and another with the release of 0.31.0.
- Using hints in 0.28.0 greatly **_improves_** performance over equivalent UDF's without hints
- Using hints in 0.31.0 greatly **_diminishes_** performance over equivalent UDF's without hints
- The rates used for the below charts use an average rate for several scalar and array UDF's

![2024-02-07_udf-regression-since-0 28 0](https://github.com/deephaven/deephaven-core/assets/120737309/fe8ce00e-3b9f-4182-9dca-46a22b143c04)

**Comment by jmao-denver** [comment]
### Auto-conversion _**disabled**_ in Python, vectorization with type hints;  cast needed, no vectorization with no-type-hints, formula is "Y = why(X)"
```
type hints, Rows / Sec: 7198272.270689589. <== 14 times faster
no type hints, Rows / Sec: 496143.91961906385
```

### Auto-conversion _**disabled**_ in Python, no vectorization at all, formula is "Y = why(X + 1)"
```
type hints, Rows / Sec: 722282.9272291749 <== same performance within the margin of error
no type hints, Rows / Sec: 689077.1888196258
```

### Auto-conversion _**enabled**_ in Python,  vectorization with type hints;  cast needed, no vectorization with no-type-hints, formula is "Y = why(X)"
```
type hints, Rows / Sec: 400916.5270778188. <==  slower, auto-conversion overhead more than offset the gain from vectorization
no type hints, Rows / Sec: 488018.12092333037
```

### Auto-conversion _**enabled**_ in Python,  no vectorization at all, formula is "Y = why(X + 1)"
```
type hints, Rows / Sec: 247269.62397384708 <== 2 times slower
no type hints, Rows / Sec: 509077.10872875294
```


```Python
import time
import numpy as np
from deephaven import empty_table, garbage_collect

def run_test():
    row_count = 10_000_000

    def why(v: int) -> np.int32:
        return v + 1

    source = empty_table(row_count).update(["X = (int)(ii % 250)"])

    begin_time = time.perf_counter_ns()
    result = source.select('Y=why(X + 1)')
    print("type hints,", 'Rows / Sec:', row_count / ((time.perf_counter_ns() - begin_time) / 1_000_000_000))
    print(result.columns[0].data_type)

    result = None
    for i in range(5):
        garbage_collect()
    
    def why(v):
        return v + 1

    begin_time = time.perf_counter_ns()
    # result = source.select('Y=why(X)').select("Y = (int)Y")
    result = source.select("Y = (int)why(X + 1)")
    print("no type hints,", 'Rows / Sec:', row_count / ((time.perf_counter_ns() - begin_time) / 1_000_000_000))
    print(result.columns[0].data_type)

    result = None
    for i in range(5):
        garbage_collect()

run_test()

```

**Comment by chipkent** [comment]
I'm trying to get my head around the relevant changes that lead to the problem.  Am I correct that these are the key files?
https://github.com/deephaven/deephaven-core/blob/main/py/server/deephaven/_udf.py
https://github.com/deephaven/deephaven-core/blob/main/engine/table/src/main/java/io/deephaven/engine/util/PyCallableWrapperJpyImpl.java

**Comment by jmao-denver** [comment]
### Array input - vectorization for type-hints, no vectorization for no-type-hints
```
--- arg/return value  auto-conversion enabled ---
type hints, Rows / Sec: 1231949.3024970691
no type hints, Rows / Sec: 1820989.1977622057
```
```
--- not arg conversion ---
type hints, Rows / Sec: 2411131.7068459815
no type hints, Rows / Sec: 1854127.122524789
```
```
--- no arg or return value conversion ---
type hints, Rows / Sec: 2948846.317343872
no type hints, Rows / Sec: 1840094.2422902663
```

### Array input - no vectorization for either
```
--- arg/return value auto-conversion enabled ---
type hints, Rows / Sec: 1034499.0853991724
no type hints, Rows / Sec: 1832391.606097296
```
```
--- no arg auto-conversion ---
type hints, Rows / Sec: 1754613.7791632663
no type hints, Rows / Sec: 2071235.161504206
```
```
--- no arg/return value auto-conversion ---
type hints, Rows / Sec: 2098357.0185048156
no type hints, Rows / Sec: 2104465.867133651
```

**Comment by jmao-denver** [comment]
### Som experiment to speed up the auto-conversion

### Scalar input/output, auto-conversion on,  removed: null/Optional check
```
type hints, Rows / Sec: 275570.23424915934
no type hints, Rows / Sec: 504334.2759002709
```

### Scalar input/output, auto-conversion on, removed:  null/Optional check, numpy scalar support in input
```
type hints, Rows / Sec: 449091.78075960197
no type hints, Rows / Sec: 520391.05714783334
```

### Array input, auto-conversion on, removed:  null/Optional check, 
```
type hints, Rows / Sec: 1336541.541810492
no type hints, Rows / Sec: 1790319.0280712221
```
### Array input, auto-conversion on, removed:  null/Optional check, lookup function call replaced with use of map
```
type hints, Rows / Sec: 1574562.8193470957
no type hints, Rows / Sec: 1750744.0249280503
```

**Comment by chipkent** [comment]
I'm looking at the perf data above.  

1) I'm not totally understanding what is going on.  Here it looks like the scalar input case is only processing 500k rows per sec while the array input case is processing 2m rows per sec.  What am I missing?  The example code is just the array case code, so I can't guess.  Maybe it is because the rows per sec is being calculated based on the input table, and the array case is only processing 10 rows?
2) The array case is only processing 10 rows, which seems extreme.  How bad are things if you process a lot of smaller rows?

I have other specific questions about what is going on.  These questions revolve around the performance of built-in python types vs numpy types (e.g. `float` vs `np.float64`), conversion times in hand written code vs annotations, etc.  I wrote this benchmark to try to dig in a bit more.  I'm not sure how to disable vectorization, so the numbers I am getting are not apples to apples.

# New benchmarks

```python
import time
import numpy as np
from deephaven import empty_table, garbage_collect

row_count = 1_000_000
source = empty_table(row_count).update(["Y = ii"])

# both type-hints numpy
def why_n_n(v: np.int64) -> np.float64:
    return v+1.2

# both type-hints native
def why_p_p(v: int) -> float:
    return v+1.2

# return type-hints numpy
def why_x_n(v) -> np.float64:
    return v+1.2

# return type-hints native
def why_x_p(v) -> float:
    return v+1.2

# param type-hints numpy
def why_n_x(v: np.int64):
    return v+1.2

# param type-hints native
def why_p_x(v: int):
    return v+1.2

# no type-hints
def why_x_x(v):
    return v+1.2

# no type-hints convert the input
def why_c_x(v):
    v = np.int64(v)
    return v+1.2

# no type-hints convert the output
def why_x_c(v):
    return np.float64(v+1.2)

# no type-hints convert both
def why_c_c(v):
    v = np.int64(v)
    return np.float64(v+1.2)

jobs = [
    ["Z = why_n_n(Y)", "numpy/numpy"],
    ["Z = why_p_p(Y)", "python/python"],
    ["Z = why_x_n(Y)", "none/numpy"],
    ["Z = why_x_p(Y)", "none/python"],
    ["Z = (double) why_n_x(Y)", "numpy/none"],
    ["Z = (double) why_p_x(Y)", "python/none"],
    ["Z = (double) why_x_x(Y)", "none/none"],
    ["Z = (double) why_c_x(Y)", "convert/none"],
    ["Z = (double) why_x_c(Y)", "none/convert"],
    ["Z = (double) why_c_c(Y)", "convert/convert"],
]

def run_test():
    for query, msg in jobs:
        begin_time = time.perf_counter_ns()
        for i in range(5):
            result = source.select(query)
        print(f"{msg} hints: {row_count * 5 / ((time.perf_counter_ns() - begin_time) / 1_000_000_000)} rows/sec ({result.columns[0].data_type})")

        # try to restore the worker to the same state
        result = None
        for i in range(5):
            garbage_collect()
        time.sleep(0.1)
        time.sleep(5)

run_test()
```

Running this code on the demo system with `0.32.0` produces:
```
numpy/numpy hints: 68825.7609555498 rows/sec (double)
python/python hints: 99940.31391955742 rows/sec (double)
none/numpy hints: 235329.6939374642 rows/sec (double)
none/python hints: 235613.83023603584 rows/sec (double)
numpy/none hints: 53120.79882927409 rows/sec (double)
python/none hints: 72962.35161478045 rows/sec (double)
none/none hints: 132157.69190853115 rows/sec (double)
convert/none hints: 84414.73315296792 rows/sec (double)
none/convert hints: 123055.80861453459 rows/sec (double)
convert/convert hints: 83034.57429840925 rows/sec (double)
```

**ALL of the rows/sec seem low.** I do not know what hardware they are on...

## Observation 1: Numpy scalar conversions are ultra slow (not a DH problem)
Numpy scalar types are much slower than python scalar types.

Converting both inputs and outputs to numpy scalars is 31% slower than using the native python types.
```
numpy/numpy hints: 68825.7609555498 rows/sec (double)
python/python hints: 99940.31391955742 rows/sec (double)
```

Floating point return conversion seems comparable.
```
none/numpy hints: 235329.6939374642 rows/sec (double)
none/python hints: 235613.83023603584 rows/sec (double)
```

Integer inputs are 27% slower.
```
numpy/none hints: 53120.79882927409 rows/sec (double)
python/none hints: 72962.35161478045 rows/sec (double)
```

Converting inputs and outputs to numpy scalars by hand is slow. 

Here the functions have no type hints and convert by hand.  Converting both values is 37% slower than the unconverted case.  The float conversion is around 6%, while the bulk of the slowdown is from the integer conversion.
```
none/none hints: 132157.69190853115 rows/sec (double)
convert/convert hints: 83034.57429840925 rows/sec (double)
convert/none hints: 84414.73315296792 rows/sec (double)
none/convert hints: 123055.80861453459 rows/sec (double)
```

## Observation 2: DH wrapper is way too slow (DH problem)
The `0.32.0` annotations are very slow.  Using an annotation to convert a Python type is 44% slower than no conversion, even though the result is identical.
```
none/none hints: 132157.69190853115 rows/sec (double)
python/none hints: 72962.35161478045 rows/sec (double)
```

Similarly, converting the input to numpy by hand is 36% slower vs 60% slower when using the annotation.
```
convert/none hints: 84414.73315296792 rows/sec (double)
numpy/none hints: 53120.79882927409 rows/sec (double)
```

This all indicates that the annotation has too much overhead.

# Considerations
1. Even unannotated cases seem excessively slow on the demo system.
2. Numpy scalars are incredibly slow.  Should we support them?  Probably not.
3. The DH annotation has way too much overhead.  It needs to be reenginnered for speed, or key parts of what it is doing need to happen in the query language.
4. Since I don't know how to turn off vectorization, I could not assess the overhead of a return type hint vs having a query string cast.  This experiment should be done since it may uncover some other clear performance problems.
5. None of the above has looked at performance tradeoffs for various ways nulls could be handled.  This concept needs to be understood in detail.
6. None of the above looks at costs associated with input or output arrays.

**Comment by jmao-denver** [comment]
> I'm looking at the perf data above.
> 
> 1. I'm not totally understanding what is going on.  Here it looks like the scalar input case is only processing 500k rows per sec while the array input case is processing 2m rows per sec.  What am I missing?  The example code is just the array case code, so I can't guess.  Maybe it is because the rows per sec is being calculated based on the input table, and the array case is only processing 10 rows?

It is a low-level math mistake. The row number after group-by should be 10 times smaller.

**Comment by jmao-denver** [comment]
### py UDF decorator by-passed entirely, no vectorization
```
numpy/numpy hints: 767347.5798621533 rows/sec (double)
python/python hints: 765443.6285388595 rows/sec (double)
```

### hard-coded long conversion for input/output (null check, NumPy type check), no vectorization
```
numpy/numpy hints: 322607.9765090602 rows/sec (double)
python/python hints: 467228.91602702165 rows/sec (double)
```

### hard-coded long conversion for input/output (no null check, no NumPy type check),  no vectorization
```
numpy/numpy hints: 532417.9882314291 rows/sec (double)
python/python hints: 544842.6423118205 rows/sec (double)
```

### hard-coded long conversion for input/output (null check, NumPy type check, _scalar() skipped), no vectorization
```
numpy/numpy hints: 545560.2847189392 rows/sec (double)
python/python hints: 547478.740932669 rows/sec (double)
```

### convert_args skipped, _scalar() skipped), no vectorization
```
numpy/numpy hints: 707053.6743619504 rows/sec (double)
python/python hints: 713683.3524860062 rows/sec (double)
```
