### ISSUE TITLE
JS API protobuf pollutes global namespace

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#5318]
**Description**

The JS API is supposed to be a self contained module, but some of the protobuf libraries we import end up using the global scope still to add `globalThis.proto`. This will cause issues in Core+ if we add multiple Core+ versions to a single instance as we need to load both versions of the JS API, but the global proto will be shared and some checks across the 2 can fail

**Additional details and attachments**

From Colin
https://github.com/protocolbuffers/protobuf-javascript?tab=readme-ov-file#the---js_out-flag

```
diff --git a/proto/raw-js-openapi/src/index.js b/proto/raw-js-openapi/src/index.js
index 55ebdf643d..364d8b9a37 100644
--- a/proto/raw-js-openapi/src/index.js
+++ b/proto/raw-js-openapi/src/index.js
@@ -1,3 +1,5 @@
+const oldGlobalThis = globalThis;
+globalThis = {};
 require("deephaven/proto/session_pb");
 require("deephaven/proto/table_pb");
 require("deephaven/proto/console_pb");
@@ -9,8 +11,10 @@ require("deephaven/proto/partitionedtable_pb");
 require("deephaven/proto/storage_pb");
 require("deephaven/proto/config_pb");
 require("deephaven/proto/hierarchicaltable_pb");
-require("Flight_pb")
-require("BrowserFlight_pb")
+require("Flight_pb");
+require("BrowserFlight_pb");
+globalThis = oldGlobalThis;
+
 var sessionService = require("deephaven/proto/session_pb_service");
 var tableService = require("deephaven/proto/table_pb_service");
 var consoleService = require("deephaven/proto/console_pb_service");
```

**Versions**
 - Deephaven: 0.33.1

**Comment by niloc132** [comment]
As the description points at, this is due to using the import_style=`commonjs` in protoc's js plugin - it looks like commonjs_strict will resolve this. In addition to avoiding placing its output directly on `window.proto` each time it is referenced, it changes what is "exported", from 

```
goog.object.extend(exports, proto.io.deephaven.proto.backplane.grpc);
```
to
```
goog.object.extend(exports, proto);
```
It isn't clear to me why this must be done - a given proto file always generates a single js file, and only can have one package in it, so it doesn't seem necessary to export the entire nested package.

Unfortunately, that change breaks compatibility with our grpc-web typescript library, which is documented to only support `commonjs` - this library does accept pull requests, but apparently will not release new versions, so if we want to fix it, we need to maintain our own fork, or patch the output in the deephaven org somewhere.

---

The other diff above was a possibly hacky way to ensure that each proto file's output doesn't get put in the true "globalThis". Unfortunately, the generated code assigns to `globalThis.proto`, then proceeds to access it as `proto` later in the file - it nearly works to instead create a temporary `globalThis.proto` and then remove it, but the `proto` global is used at runtime, not just as objects are being declared. So we rule this out too.

---

I'm not sure what the cleanest answer is going to be here - to rewrite generated files from one of the above, to try some trickery with changing globalThis when executing require/imports, or to look into our just writing our own codegen so we control it and can maintain it.

**Comment by niloc132** [comment]
Some options:

1. sed/etc to rewrite the last line of the protoc-gen-js output to export only the file's service/messages, rather than re-namespace everything when commonjs_strict is used. Gross, but only one line changes.
2. Explore hacks around faking globalThis for a single js file - can we use webpack to wrap this, or is there some other idiom we could consider?
3. generate a shim es6 module to sit between pb and service, so that the service can import the shim, which reexports the proto without the namespace. Less gross, but requires a whole protoc plugin (or a manual `.jsm` for each `.proto`), and a bit of additional build glue to arrange the files with the intermediate shim.
4. Give up on protoc-gen-ts entirely, and implement a protoc plugin that generates java types. This is probably inevitable anyway (since google-protobuf.js is barely maintained, protobuf.js deliberately has precision issues), but now may not be the right time (though with #188 being actively developed, it might make sense to do it soon).

I'm leaning towards a fully manual option 3 in lieu of some dirty hack we can do for option 2. Then, once #3133 and #188 are resolved, aim for fully owning this tooling, if the tools we use from the ecosystem haven't resolved this.
