### ISSUE TITLE
JS API format datetime throwing/wrong in some subsecond cases

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#5609]
**Description**

It seems that the GWT version bump in #5576 broke our JS API datetime format method. Specifically it seems there is now a bounds check by GWT on substrings where previously there was none. This worked b/c the JS method called accepts negative indexes. Now GWT is checking the bounds and throwing instead.

Colin has a test using the format string `'yyyy-MM-dd HH:mm:ss.SSSSSS'` w/ the value `'1566747296000000000'`

**Comment by niloc132** [comment]
https://github.com/gwtproject/gwt/commit/657ae98c5d8bb20b67639d3175cf843e86ce3cda added bounds checks where previously none existed. Other usages of String.substring() should be audited to ensure we aren't hitting this anywhere else.

**Comment by niloc132** [comment]
It turns out there's a real bug here too, this just pointed it out - any time that exception would be thrown, previously we would have just written the wrong subsecond value. 

Steps to repro in older builds:
 * visit http://localhost:10000/jsapi/format.html
 * enter a datetime format with 6 `S`s, to show microsecond precision (e.g. `yyyy_MM_dd'T'HH-mm-ss.SSSSSS z` or `SSSSSS`)
 * enter a nanosecond timestamp with all 0s for subsecond places (e.g. `1566747296000000000`)
 * Click "Render nanoseconds as date

Expected: 6 0s drawn for subsecond precision. 
Actual: 8 0s drawn

This will break with any number of `S`s greater than three, less than or equal to 9.
