### ISSUE TITLE
JS API: Failure to handle RowSets with large numbers of ranges

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#6177]
Test query:
```
input=emptyTable(1_000_000_000).view("A=ii").where("A % 2 == 0")
```

**Comment by niloc132** [comment]
It turns out that, in Chrome at least, JS fixed arrays are limited in size to something like 112,813,857 elements, rather than the advertised spec size of `(2^32)-1`, or 4,294,967,296. The limit _should_ be higher, but the resizing logic has a bug that prevents it from hitting its _actual_ max of 134,217,726.

https://issues.chromium.org/issues/42210629
https://github.com/nodejs/node/issues/47928#issuecomment-1540947435

Automatically flattening viewports will get us past this issue, since this bug means that we can't track more than 100 million of anything on the client without resorting to wasm or typedarrays for everything.

**Comment by niloc132** [comment]
We're going to punt on this after @nbauernfeind's "effectively flatten viewports on the server" feature - that will reduce the use case to non-viewport subscriptions, which _largely_ is restricted to charts. Those subscriptions have a hard upper limit well under 1m rows at creation time, though technically we do allow them to grow beyond that point without downsampling or other measures. So we still could get into trouble there, but we haven't yet in 5+ years of supporting this, and JS makes it too difficult to handle this nicely.

Plus the fact that in memory this would be massive, and chokes the browser downloading and processing the data. Someday we could end up with flight/barrage processing in wasm and deal with more than 112m row subscriptions definitively, but we don't have the use case to justify that work at this time.

Closing as dup of #6039.
