### ISSUE TITLE
Parquet: Support non-UTC timestamps

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#976]
Running (in groovy):
```
t = io.deephaven.db.tables.utils.ParquetTools.readTable("/data/parquetFiles/eth_v2_p2_cBROTLI.parquet")
```
Would result in:
```
io.deephaven.UncheckedDeephavenException: Unable to read column [tpep_pickup_datetime]: TimestampLogicalType, isAdjustedToUTC=false, unit=MICROS not supported
```
If we didn't have a fortunate schema conversion error that effectively treats the timestamps as UTC. We would like to reverse the error and properly support zoned timestamps. Presumably we could specify a timezone in read instructions.

We *do* have limited support in: `io.deephaven.db.v2.locations.parquet.topage.ToDBDateTimePageFromInt96`
Likely the reference time zone used there should be moved out to `ParquetInstructions`. Then we just need to integrate those instructions into the Int96 support and into the more standard datetime fields.

**Comment by rcaudy** [comment]
So, we have a fairly buggy bit of schema reader code in use right now. One side effect is that we totally ignore that a timestamp might not be UTC, except for the unfortunate hack for int96 mentioned in the description.

**Comment by malhotrashivam** [comment]
**Parquet handling of timestamps:**

TIMESTAMP type has two extra fields: isAdjustedToUTC (= true/false), unit (= MILLIS/MICROS/NANOS).

- TIMESTAMP with `isAdjustedToUTC=true` is defined as the time elapsed since the Unix epoch. So we can translate such a instant to UTC time and then adjust it to local timezone. For example, TIMESTAMP(isAdjustedToUTC=true, unit=MILLIS) value of 172800000 corresponds to 1970-01-03 00:00:00 UTC and the corresponding local time will change according to timezone.
- TIMESTAMP with `isAdjustedToUTC=false` represents time fields in a local timezone, regardless of what local timezone is. For example, TIMESTAMP(isAdjustedToUTC=false, unit=MILLIS) value of 172800000 corresponds to 1970-01-03 00:00:00 in any timezone.

More details in [official docs here.](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md)

**Comment by devinrsmith** [comment]
I think on a column-by-column basis we should be able to add in an assumed timezone; for example, the [NYC taxi dataset](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page) e, we can assume that the timezone is NYC timezone. As it stands today, we read this in as a LocalDateTime.

**Comment by malhotrashivam** [comment]
Original issue completed as part of #4801.
